# SITE SETTINGS
title:                Benjamin Kinzer
subtitle:             Creative Director and Designer
email:                ben@benjaminkinzer.com
author:               Benjamin Kinzer
description:          Site description here.
baseurl:              "" # subpath if necessary, e.g. /blog/
url:                  "http://benjaminkinzer.com" # base url http://url.com

# GOOGLE ANALYTICS
google_analytics:     UA-XXXXX-X

# BUILD SETTINGS
markdown:             kramdown
permalink:            pretty
paginate:             3
sass:
  sass_dir:           /assets/_sass/
  compressed:         true

# FEATURE SETS
show_related_posts:   false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# SOCIAL
show_social:          false
github_username:
twitter_username:
linkedin_username:
flattr_button:

# Post sharing icons
show_sharing:         false
share_text:           'Share this post!'
# Change to 'true' to enable individual icons
share_facebook:       false
share_twitter:        false
share_googleplus:     false
share_linkedin:       false
share_digg:           false
share_tumblr:         false
share_reddit:         false
share_stumbleupon:    false
share_hackernews:     false

# GEMS
gems:
  - jekyll-sitemap